<a href="https://colab.research.google.com/github/erichsiao1106/DL0820/blob/master/RNN_family.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [2]:
# Sample: 1
# Sequence Length: 5
# feature dimension: 8

inputs = tf.random.normal([1, 5, 8])

# tf.keras.layers.LSTM

In [3]:
output = layers.LSTM(units=3)(inputs)
print(output.shape)

(1, 3)


In [4]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(3, return_sequences=True, return_state=True)(inputs)

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.10407593 -0.10250396 -0.02734842]
  [ 0.04934055 -0.02268938  0.14708896]
  [-0.1384705  -0.07604447  0.14647514]
  [-0.26471975 -0.17783964  0.00885056]
  [-0.01738939 -0.09811804  0.143015  ]]], shape=(1, 5, 3), dtype=float32)
final_hiden_state (h):  (1, 3) tf.Tensor([[-0.01738939 -0.09811804  0.143015  ]], shape=(1, 3), dtype=float32)
final_cell_state (c):  (1, 3) tf.Tensor([[-0.05459881 -0.2306486   0.22873387]], shape=(1, 3), dtype=float32)


# tf.keras.layers.GRU

In [ ]:
output = layers.GRU(units=3)(inputs)
print(output.shape)

(1, 3)


In [ ]:
whole_sequence_output, final_state = layers.GRU(3, return_sequences=True, return_state=True)(inputs)

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.08479704  0.13525589  0.55395424]
  [-0.4651748   0.57352954  0.54958713]
  [ 0.7174084   0.5108517   0.3651455 ]
  [-0.0230526  -0.0093562   0.440216  ]
  [ 0.40535817  0.742209    0.5817626 ]]], shape=(1, 5, 3), dtype=float32)
final_state (h):  (1, 3) tf.Tensor([[0.40535817 0.742209   0.5817626 ]], shape=(1, 3), dtype=float32)


# tf.keras.layers.Bidirectional

In [5]:
output = layers.Bidirectional(layers.LSTM(10))(inputs)
print(output.shape)

(1, 20)


In [ ]:
# merge_mode: Sum
output = layers.Bidirectional(layers.LSTM(10), merge_mode='sum')(inputs)
print(output.shape)

(1, 10)


In [ ]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(10, return_sequences=True))(inputs)
print(output.shape)

(1, 5, 20)


In [ ]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(2, return_sequences=True, return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 4) tf.Tensor(
[[[ 0.29163426 -0.1556068   0.00640483 -0.08145556]
  [ 0.08594795  0.00379655 -0.05019695 -0.07782163]
  [ 0.06150479 -0.08528213 -0.03621112 -0.13300344]
  [-0.21334249  0.01168969  0.01887869 -0.16888788]
  [-0.5033704   0.04816216 -0.11542789 -0.00869413]]], shape=(1, 5, 4), dtype=float32)
forward_h :  (1, 2) tf.Tensor([[-0.5033704   0.04816216]], shape=(1, 2), dtype=float32)
forward_c :  (1, 2) tf.Tensor([[-1.0085428   0.27935323]], shape=(1, 2), dtype=float32)
backward_h :  (1, 2) tf.Tensor([[ 0.00640483 -0.08145556]], shape=(1, 2), dtype=float32)
backward_c :  (1, 2) tf.Tensor([[ 0.00671035 -0.5228235 ]], shape=(1, 2), dtype=float32)


## Many-to-one

In [ ]:
input = layers.Input(shape=(5, 8))
x = layers.LSTM(128)(input)
ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_17 (LSTM)               (None, 128)               70144     
_________________________________________________________________
dense (Dense)                (None, 10)                1290      
Total params: 71,434
Trainable params: 71,434
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# multi-layer
input = layers.Input(shape=(5, 8))
x = layers.LSTM(128, return_sequences=True)(input)
x = layers.LSTM(10)(x)
ouput = layers.Dense(10)(x)
model = models.Model(input, ouput)
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_27 (LSTM)               (None, 5, 128)            70144     
_________________________________________________________________
lstm_28 (LSTM)               (None, 10)                5560      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                110       
Total params: 75,814
Trainable params: 75,814
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [ ]:
input = layers.Input(shape=(50, 8))
x = layers.LSTM(10, return_sequences=True)(input)
ouput = layers.TimeDistributed(layers.Dense(20))(x)
model = models.Model(input, ouput)
model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 50, 8)]           0         
_________________________________________________________________
lstm_30 (LSTM)               (None, 50, 10)            760       
_________________________________________________________________
time_distributed_1 (TimeDist (None, 50, 20)            220       
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq